# -*- coding: utf-8 -*-
"""Binomial tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10lqYJMJhTtrEEZeZiMAMV_67R8i8vgJ0
"""

import numpy as np
import matplotlib.pyplot as plt

K= 120
S0 = 115
sigma= 0.5
r= 0.005
T =1
N= 20
type_ = 'C'

def binomial_tree(K, S0, sigma, r, T, N, type_='C'):
  dt = T/N
  a = np.exp(r*dt)
  u= np.exp(sigma*np.sqrt(dt))
  d= np.exp(-sigma*np.sqrt(dt))
  p = (a-d)/(u-d)
  disc = np.exp(-r*dt)
  S = S0 * u**np.arange(N, -1, -1) * d**np.arange(0, N+1)


  if type_ == 'C':
    O = np.maximum(S-K, 0)

  else:
    O = np.maximum(K-S, 0)

  for i in np.arange(N-1, -1, -1):
    O = disc*(O[1:i+2]*p+O[:i+1]*(1-p))

  return O[0]

binomial_tree(K, S0, sigma, r, T, N, type_=type_)

