# -*- coding: utf-8 -*-
"""comparison data vs info of the day.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15TjVRA9Xs8mElsWlh4MLWI4ugzgq4DM9
"""

import pandas as pd
import yfinance as yf
from gnews import GNews
from transformers import pipeline
from datetime import datetime, timedelta
import torch
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm

# Paramètres
ticker = "NVDA"
keyword = "Nvidia stock"
days_history = 730

google_news = GNews(language='en', country='US', max_results=20)
daily_news_storage = []
current_date = datetime.now()

print(f"🚀 Scraping de {ticker} en cours...")

for i in tqdm(range(days_history)):
    target_date = current_date - timedelta(days=i)
    google_news.start_date = (target_date.year, target_date.month, target_date.day)
    google_news.end_date = (target_date.year, target_date.month, target_date.day)

    try:
        batch = google_news.get_news(keyword)
        if batch:
            for article in batch:
                daily_news_storage.append({
                    'Date': target_date.replace(hour=0, minute=0, second=0, microsecond=0),
                    'Title': article['title']
                })
    except:
        continue

df_raw_news = pd.DataFrame(daily_news_storage)
print(f"✅ {len(df_raw_news)} titres récupérés.")

print("🧠 Analyse FinBERT en cours...")
classifier = pipeline('sentiment-analysis', model='ProsusAI/finbert')

def get_dynamic_score(text):
    result = classifier(text[:128])[0]
    label = result['label']
    conf = result['score']

    if label == 'positive': return conf    # +Confiance
    elif label == 'negative': return -conf  # -Confiance
    else: return 0                          # Neutre pur

# Application et groupement par jour
df_raw_news['Score'] = [get_dynamic_score(t) for t in tqdm(df_raw_news['Title'])]
df_daily_sentiment = df_raw_news.groupby('Date')['Score'].mean().reset_index()

print("✅ Sentiment calculé sur l'échelle -1 / +1.")

print("📈 Récupération des prix et calcul des indicateurs (Volume & RSI)...")

# Dates
start_date = df_daily_sentiment['Date'].min()
end_date = df_daily_sentiment['Date'].max() + timedelta(days=1)

# 1. Download (marge de 30 jours pour les calculs techniques)
stock_data = yf.download(ticker, start=start_date - timedelta(days=30), end=end_date, progress=False)

# 2. Nettoyage Multi-Index
if isinstance(stock_data.columns, pd.MultiIndex):
    stock_data.columns = stock_data.columns.get_level_values(0)

# 3. Volume Ratio
stock_data['Vol_Moyenne_20j'] = stock_data['Volume'].rolling(window=20).mean()
stock_data['Volume_Ratio'] = stock_data['Volume'] / stock_data['Vol_Moyenne_20j']

# 4. RSI
delta = stock_data['Close'].diff()
gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
rs = gain / loss
stock_data['RSI'] = 100 - (100 / (1 + rs))

# 5. Normalisation et Fusion
stock_data = stock_data.reset_index()
stock_data['Date'] = pd.to_datetime(stock_data['Date']).dt.tz_localize(None).dt.normalize()
df_daily_sentiment['Date'] = pd.to_datetime(df_daily_sentiment['Date']).dt.tz_localize(None).dt.normalize()

merged = pd.merge(stock_data, df_daily_sentiment, on='Date', how='inner')
merged = merged.dropna(subset=['Close', 'Score', 'Volume_Ratio', 'RSI'])

print(f"✅ Fusion terminée ! On a {len(merged)} jours de données propres.")

# 1. Création de la Target (Prédiction J+1)
merged['Prix_Demain'] = merged['Close'].shift(-1)
merged['Target'] = (merged['Prix_Demain'] > merged['Close']).astype(int)

# 2. Analyse de Corrélation
colonnes_ml = ['Close', 'Score', 'Volume_Ratio', 'RSI', 'Target']
matrice_corr = merged[colonnes_ml].corr()

print(f"\n📊 CORRÉLATION DIRECTE : {merged['Score'].corr(merged['Close']):.4f}")

# 3. Graphique Temporel Complet
fig, ax1 = plt.subplots(figsize=(15, 7))

# Prix (Axe Gauche)
ax1.plot(merged['Date'], merged['Close'], color='blue', label='Prix Action', alpha=0.3)
ax1.set_ylabel('Prix ($)', color='blue')

# Sentiment (Axe Droit)
ax2 = ax1.twinx()
ax2.scatter(merged['Date'], merged['Score'], color='orange', alpha=0.3, s=10, label='Score Quotidien')
merged['Score_Lissé'] = merged['Score'].rolling(window=5).mean()
ax2.plot(merged['Date'], merged['Score_Lissé'], color='red', label='Tendance (MA 5j)', linewidth=2)
ax2.axhline(0, color='black', linestyle='--', alpha=0.3)
ax2.set_ylabel('Sentiment IA', color='red')

plt.title(f"Analyse {ticker} : Corrélation Prix vs Sentiment")
ax1.legend(loc='upper left'); ax2.legend(loc='upper right')
plt.show()

# 4. Heatmap de Corrélation
plt.figure(figsize=(8, 6))
sns.heatmap(matrice_corr, annot=True, cmap='coolwarm', center=0)
plt.title("Matrice de Corrélation des Features")
plt.show()