# -*- coding: utf-8 -*-
"""sentiment analysis stock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XDoNpZAeHVaQojCy-AI0IaLfD-fcmqwr
"""

from urllib.request import urlopen, Request
from bs4 import BeautifulSoup
import pandas as pd
from transformers import pipeline

ticker = 'MSFT'
url = f'https://finviz.com/quote.ashx?t={ticker}'
req= Request(url=url, headers ={'User-Agent':'Mozilla/5.0'})
response = urlopen(req)
html = BeautifulSoup(response, 'html.parser')
news_table = html.find(id='news-table')
df = pd.read_html(str(news_table))
df

parsed_news =[]
for row in news_table.find_all('tr'):
  if row.a is None:
    continue
  title = row.a.text
  parsed_news.append(title)
for t in parsed_news[:10]:
  print(f'-{t}')

classifier = pipeline('sentiment-analysis', model='ProsusAI/finbert')
def rate_out_of_10(texte):
  resultat =classifier (texte)[0]
  label = resultat['label']
  score = resultat['score']
  if label == 'positive':
    note = 5 + (score*5)
  elif label == 'negative':
    note = 5 - (score*5)
  else:
    note = 5.0
  return note

df = pd.DataFrame(parsed_news, columns=['news_title'])
df = df.head(10)
df['Note_IA'] = df['news_title'].apply(rate_out_of_10)
df

df['Note_IA'].mean()