# -*- coding: utf-8 -*-
"""Test fuzzy time series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152jWNMStqTRDjEqNvSmXnIWlIQcewajo
"""

!pip install pyFTS SimpSOM

import numpy as np
if not hasattr(np, 'int'):
    np.int = np.int64
    np.float = np.float64
    np.bool = bool
import matplotlib.pyplot as plt
import pandas as pd

from pyFTS.data import NASDAQ, SP500
datasets = {
    "S&P 500": SP500.get_data()[11500:16000],
    "NASDAQ": NASDAQ.get_data()
}

train_split = 2000

from pyFTS.common import Transformations
tdiff = Transformations.Differential(1)

fig, ax = plt.subplots (nrows=2, ncols=2)
for count, (dataset_name, dataset) in enumerate(datasets.items()):
  dataset_diff = tdiff.apply(dataset)
  ax[0][count].plot(dataset)
  ax[1][count].plot(dataset_diff)
  ax[0][count].set_title(dataset_name)

from pyFTS.models import song
from pyFTS.partitioners import Grid
models = {}
for count, (dataset_name, dataset) in enumerate(datasets.items()):
  partitioner_diff = Grid.GridPartitioner(data=dataset, npart = 15, transformation = tdiff)
  model = song.ConventionalFTS(partitioner=partitioner_diff)
  model.name = dataset_name
  model.append_transformation(tdiff)
  model.fit(
      dataset[:train_spilt],
      order =1
  )
  models[dataset_name] = model

_, ax = plt.subplots(nrows=2, ncols=1, figsize=[12, 6])
for count, (dataset_name, dataset) in enumerate(datasets.items()):
  ax[count].plot(dataset[train_split:train_split+200])
  model = models[dataset_name]
  forecasts = model.predict(dataset[train_split:train_split+200],
  steps_ahead=1)
  ax[count].plot(forecasts, c='r')
  ax[count].set_title(dataset_name)
plt.tight_layout()

from pyFTS.benchmarks import Measures
rows = []
for count, (dataset_name, dataset) in enumerate(datasets.items()):
  row = [dataset_name]
  test = dataset[train_split:train_split+200]
  model = models[dataset_name]
  row.extend(Measures.get_point_statistics(test, model))
  rows.append(row)

pd.DataFrame(
    rows, columns=["Dataset", "RMSE", "MAPE", "Theil's U"]
).set_index("Dataset")