# -*- coding: utf-8 -*-
"""Test volatilité implicite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12sQpHhdXtNG5wo1I9doOJvsfKDkJfrLC
"""

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Charger 1 an de données quotidiennes d'Apple
data = yf.download("AAPL", period="1y", interval="1d")

# Calcul des rendements log
data["returns"] = np.log(data["Close"] / data["Close"].shift(1))

# Volatilité historique glissante sur 21 jours (environ 1 mois)
data["vol_hist"] = data["returns"].rolling(window=21).std() * np.sqrt(252)

opt = yf.Ticker("AAPL")
vol_impl = opt.options  # Liste des dates d'expiration disponibles
print(vol_impl[:5])     # Pour voir les maturités les plus proches

expiry = vol_impl[0]  # prochaine échéance
opt_chain = opt.option_chain(expiry)
vol_impl_call = opt_chain.calls['impliedVolatility'].mean()
print(f"Volatilité implicite (échéance {expiry}) : {vol_impl_call:.2%}")

plt.figure(figsize=(10,5))
plt.plot(data.index, data["vol_hist"], label="Volatilité historique (21j)")
plt.axhline(y=vol_impl_call, color='r', linestyle='--', label=f"Vol implicite {expiry}")
plt.title("Volatilité historique vs implicite - AAPL")
plt.ylabel("Volatilité annualisée")
plt.legend()
plt.grid(True)
plt.show()

vix = yf.download("^VIX", period="1y")
plt.plot(vix.index, vix["Close"]/100, label="Vol implicite (VIX)")

spx = yf.download("^GSPC", period="1y")
spx["returns"] = np.log(spx["Close"]/spx["Close"].shift(1))
spx["vol_hist"] = spx["returns"].rolling(21).std() * np.sqrt(252)

plt.figure(figsize=(10,5))
plt.plot(spx.index, spx["vol_hist"], label="Vol historique S&P 500")
plt.plot(vix.index, vix["Close"]/100, label="Vol implicite (VIX)")
plt.legend(); plt.grid(True)
plt.title("Volatilité historique vs implicite (VIX)")
plt.show()

