# -*- coding: utf-8 -*-
"""Test model prophet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vDm2Tof2j48M89FLjzr5-aqXruckunKj
"""

!pip install prophet

import pandas as pd
import numpy as np
from pandas_datareader.data import DataReader
from datetime import datetime
from prophet import Prophet
import yfinance as yf

ticker = ['JPM']
ticker_data = yf.download(ticker, interval = '1d', start= '2001-06-01', end=('2021-06-01'))
df = pd.DataFrame(ticker_data)

df.head()

df.drop(columns=['Open', 'High', 'Low', 'Volume'], inplace=True)

df.columns = df.columns.get_level_values(0)

df = df.reset_index()
df_prophet = df[['Date', 'Close']].rename(columns={'Date': 'ds', 'Close': 'y'})

df_prophet = df_prophet.dropna()

print("Type de df:", type(df))
print("Colonnes:", df.columns)
print("Type des colonnes:", type(df.columns))
print("\nType de Close:", type(df['Close']))
print("Shape de Close:", df['Close'].shape)

forecaster = Prophet()
forecaster.fit(df_prophet)

future=forecaster.make_future_dataframe(periods=90)
forecast=forecaster.predict(future)
forecaster.plot(forecast, figsize=(12, 8))

df_prophet.head()

